# Generated by Django 3.2.3 on 2021-05-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='region',
            name='transliteration',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
