# Generated by Django 3.2.3 on 2021-05-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
